### ISSUE TITLE
No details on this project.

### ISSUE THREAD

**Issue by alexey-milovidov** [Sanmayce/Schmekeriada#1]

**Comment by Sanmayce** [comment]
Hi @alexey-milovidov, still cannot find time to set my GitHub, yet here are some modern benchmarks:
https://www.overclock.net/threads/the-definitive-quicksort-benchmark.1800616/page-2#post-29044397

**Comment by Sanmayce** [comment]
Hi @alexey-milovidov, just kinda cloned the homepage here, the tar contains everything.

**Comment by alexey-milovidov** [comment]
Thank you! Now I can test it...

**Comment by alexey-milovidov** [comment]
#2
